#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean

on:
  #Release å‘å¸ƒè§¦å‘
  #release:
  #  types: [published]
 
  #ç¼–è¾‘è§¦å‘
  push:
    branches: 
      - master
  
  #å®šæ—¶è§¦å‘
  #schedule:
  #  - cron: 0 1 * * *

  #ç‚¹èµè§¦å‘
  #watch:
  #  types: [started]

env:
  # æº
  REPO_URL: https://github.com/coolsnowwolf/lede
  # åˆ†æ”¯
  REPO_BRANCH: master
  # PassWallæ’ä»¶åŒ…
  #EX_PKG: true
  # è„šæœ¬
  #DIY_SH: OpenWrt-R7800-Lean.sh
  DIY_SH: customize.sh
  # å¼€å¯SSHè¿æ¥
  SSH_ACTIONS: true
  # ä¸Šä¼ åˆ†æ”¯
  #UPLOAD_BRANCH: false
  # åˆ†æ”¯
  #BRANCH: R7800-Lean
  # Github ç”¨æˆ·å
  #GITHUB_USER_NAME: badsirius
  # Github é‚®ç®±
  #GITHUB_USER_EMAIL: ${{ secrets.EMAIL }}
  # Github
  #GITHUB: github.com/badsirius/actions-openwrt-r7800.git
  # ä¸Šä¼ BINæ‰€æœ‰å†…å®¹
  #UPLOAD_BIN_DIR: true
  # ä¸Šä¼ å›ºä»¶
  #UPLOAD_FIRMWARE: true
  # ä¸Šä¼ åˆ°å¥¶ç‰›å¿«ä¼ 
  #UPLOAD_COWTRANSFER: true
  # åˆ›å»º+ä¸Šä¼ å‘å¸ƒ
  #CREATE_RELEASE: true
  # ç¼–è¯‘è€…
  #BUILD_USER: badsirius
  # å¾®ä¿¡é€šçŸ¥
  #SEND_WECHAT_MSG: false

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id

    steps:
    # æ ¡éªŒæœ¬åœ°æ–‡ä»¶
    - name: Checkout
      uses: actions/checkout@main

    # åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #docker rmi $(docker images -q)
        #sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        #sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar re2c swig rsync iptables coreutils bash ca-certificates ipset
        #sudo -E ln -sf /usr/bin/gcc-8 /usr/bin/gcc
        #sudo -E ln -sf /usr/bin/g++-8 /usr/bin/g++
        #sudo -E ln -sf /usr/bin/gcc-ar-8 /usr/bin/gcc-ar
        #sudo -E ln -sf /usr/bin/gcc-nm-8 /usr/bin/gcc-nm
        #sudo -E ln -sf /usr/bin/gcc-ranlib-8 /usr/bin/gcc-ranlib
        #sudo -E apt-get autoremove -y --purge
        #sudo -E apt-get clean -y
        #sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php

    # å…‹éš†æºä»£ç  By bobotoy
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(TZ=UTC-8 date "+%Y-%m-%d")"
        #åŠ å…¥SSR Plus
        sed -i '11s/#//' feeds.conf.default
        sed -i '11a src-git lienol https://github.com/Lienol/openwrt-package' feeds.conf.default
 
    # å¢åŠ  PassWall æ’ä»¶æº By rohu168
    #- name: Update and install feeds passwall
    #  if: env.EX_PKG == 'true'
    #  run: |
    #    chmod +x ssr-plus_passwall.sh && cp ssr-plus_passwall.sh ./openwrt && cd openwrt && ./ssr-plus_passwall.sh
        
    # æ›´æ–°æº sed -i 's/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
         
    - name: Clone openclash code
      run: |
        git clone https://github.com/chancat87/OpenClash.git
        mv OpenClash/luci-app-openclash/ openwrt/package/
        
    - name: Clone clash code
      run: |
        cd openwrt/package
        git clone https://github.com/frainzy1477/luci-app-clash.git

    - name: Clone Hello World code
      run: |
        cd openwrt/package/lean
        #git lua-maxminddb ä¾èµ–
        git clone https://github.com/jerrykuku/lua-maxminddb.git  
        git clone https://github.com/jerrykuku/luci-app-vssr.git 
      
    - name: Clone adGuardhome code
      run: |
        cd openwrt/package
        git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
                
    - name: Clone dockerman code
      run: |
         git clone https://github.com/lisaac/luci-lib-docker.git
         mv luci-lib-docker/collections/luci-lib-docker openwrt/package/
         git clone https://github.com/lisaac/luci-app-dockerman.git
         mv luci-app-dockerman/applications/luci-app-dockerman openwrt/package/

    - name: Fix dockerman code
      run: |
        cd openwrt/package/luci-app-dockerman
        sed -i '17d' Makefile
        sed -i '16a include $(TOPDIR)/feeds/luci/luci.mk' Makefile
     
    - name: Update feeds for smartdns
      run: |
        cd openwrt
        ./scripts/feeds update -a
        
    - name: Clone smartdns code
      run: |
        cd openwrt
        WORKINGDIR="`pwd`/feeds/packages/net/smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        wget https://github.com/pymumu/openwrt-smartdns/archive/master.zip -O $WORKINGDIR/master.zip
        unzip $WORKINGDIR/master.zip -d $WORKINGDIR
        mv $WORKINGDIR/openwrt-smartdns-master/* $WORKINGDIR/
        rmdir $WORKINGDIR/openwrt-smartdns-master
        rm $WORKINGDIR/master.zip
  
        LUCIBRANCH="lede"
        WORKINGDIR="`pwd`/feeds/luci/applications/luci-app-smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        wget https://github.com/pymumu/luci-app-smartdns/archive/${LUCIBRANCH}.zip -O $WORKINGDIR/${LUCIBRANCH}.zip
        unzip $WORKINGDIR/${LUCIBRANCH}.zip -d $WORKINGDIR
        mv $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}/* $WORKINGDIR/
        rmdir $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}
        rm $WORKINGDIR/${LUCIBRANCH}.zip
        
    - name: Fix smartdns code
      run: |
        cd openwrt/feeds/luci/applications/luci-app-smartdns
        sed -i '24d' Makefile
        sed -i '23a include $(TOPDIR)/feeds/luci/luci.mk' Makefile
        
    - name: Fix compat code
      run: |
        cd openwrt/feeds/luci/modules/luci-compat
        sed -i '17d' Makefile
        sed -i '16a include $(TOPDIR)/feeds/luci/luci.mk' Makefile
            
    #- name: Update Feeds
    #  if: env.REPO_URL != 'https://github.com/coolsnowwolf/lede'
    #  working-directory: ./openwrt
    #  run:  |
    #    ./scripts/feeds clean
    #    ./scripts/feeds update -a

    ## å®‰è£…æº
    #- name: Install Feeds
    #  if: env.REPO_URL != 'https://github.com/coolsnowwolf/lede'
    #  working-directory: ./openwrt
    #  run:  ./scripts/feeds install -a

    - name: Update & Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Download package
      id: package
      run: |
        cd openwrt
        #make download -j8
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        #åŸç¨‹å¼ç¢¼ï¼šx86_64 å¯ç·¨è­¯å®Œæˆ ä½† R7800 æœƒç·¨è­¯å¤±æ•—
        make -j$(nproc) || make -j1 V=s
        #æ”¹æˆä¸‹é¢ç¨‹å¼ç¢¼ï¼š(ç·¨è­¯å¤±æ•—)
        #make -j1 V=s
        echo "::set-output name=status::success"

    - name: Upload bin directory
      #uses: actions/upload-artifact@master
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_directory
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$(pwd)"
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      #uses: actions/upload-artifact@master
      uses: actions/upload-artifact@main
      #if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        #name: OpenWrt_firmware
        #path: ${{ env.FIRMWARE }}
        name: OpenWrt
        path: openwrt/bin





    ## åŠ è½½è‡ªå®šä¹‰é…ç½®æ–‡ä»¶
    #- name: Load Custom Configuration
    #  run: |
    #    [ -e files ] && mv files openwrt/files
    #    #[ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
    #    #chmod +x ./customize.sh && ./customize.sh
    #    #cd openwrt && make defconfig
        
    #    chmod +x $DIY_SH
    #    cd openwrt
    #    ../$DIY_SH
    #    make defconfig

    ## SSHè¿æ¥
    #- name: Debugging with tmate SSH
    #  uses: csexton/debugger-action@master
    #  if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

    ## ä¸‹è½½è½¯ä»¶åŒ…
    #- name: Make Download
    #  working-directory: ./openwrt
    #  id: package
    #  run: |
    #    make download -j8
    #    #make download -j$(nproc)
    #    find dl -size -1024c -exec ls -l {} \;
    #    find dl -size -1024c -exec rm -f {} \;
    
    ## ç¼–è¯‘å›ºä»¶
    #- name: Compile Firmware
    #  working-directory: ./openwrt
    #  id: compile
    #  run: |
    #    echo -e "$(nproc) thread compile"
    #    make -j$(nproc) || make -j1 V=s
    #    echo "::set-output name=status::success"        
    
    ## ä¸Šä¼ åˆ°åˆ†æ”¯ By yfdoor
    #- name: Upload Branch
    #  if: steps.compile.outputs.status == 'success' && env.UPLOAD_BRANCH == 'true' && !cancelled() 
    #  env:
    #      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    #  run: |
    #      cd openwrt/bin/targets/*/*
    #      rm -rf *uImage
    #      rm -rf *.manifest
    #      rm -rf *.seed
    #      rm -rf *.buildinfo
    #      rm -rf *.tar.xz
    #      cd /home/runner/work/actions-openwrt-r7800/actions-openwrt-r7800/openwrt/bin
    #      git init
    #      git config user.name $GITHUB_USER_NAME
    #      git config user.email $GITHUB_USER_EMAIL
    #      git add .
    #      git commit -m "Update OpenWrt_"$BRANCH
    #      git push --force --quiet https://${{ secrets.RELEASE_TOKEN }}@$GITHUB HEAD:OpenWrt-$BRANCH
    
    
    ## æ•´ç†binæ–‡ä»¶
    #- name: Organize Bin Files 
    #  id: organize4binfiles
    #  if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
    #  run: |
    #    cd openwrt/bin/targets/*/*
    #    rm -rf *uImage
    #    rm -rf *.manifest
    #    rm -rf *.seed
    #    rm -rf *.buildinfo
    #    rm -rf *.tar.xz
    #    cd ../../..
    #    zip r7800-all-bins.zip ./*
    #    mkdir upload
    #    mv r7800-all-bins.zip ./upload
    #    cd upload
    #    echo "::set-env name=BIN::$PWD"
    #    echo "::set-output name=status::success"
        
    ## ä¸Šä¼  Bin æ–‡ä»¶å¤¹    
    #- name: Upload all-bin To CowTransfer
    #  if: steps.organize4binfiles.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
    #  run: |
    #    curl -fsSL git.io/file-transfer | sh
    #    ./transfer cow --block 2621440 -s -p 99 -t 3 --hash --no-progress ${BIN} 2>&1 | tee cowtransfer.log
    #    echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
    #    echo "::set-env name=IPK_URL::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"

    ## æ•´ç†æ–‡ä»¶
    #- name: Organize Files
    #  id: organize
    #  if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
    #  run: |
    #    mv openwrt/.config openwrt/bin/targets/*/*
    #    mv openwrt/bin/upload/*.zip openwrt/bin/targets/*/*
    #    cd openwrt/bin/targets/*/*
    #    rm -rf packages
    #    rm -rf *uImage
    #    rm -rf *.manifest
    #    rm -rf *.seed
    #    rm -rf *.buildinfo
    #    rm -rf *.tar.xz
    #    echo "::set-env name=FIRMWARE::$PWD"
    #    echo "::set-output name=status::success"
    
    ## ä¸Šä¼ å›ºä»¶
    #- name: Upload Firmware Directory
    #  uses: actions/upload-artifact@main
    #  if: steps.organize.outputs.status == 'success' && !cancelled()
    #  with:
    #    name: ${{ env.BUILD_USER }}-${{ env.DATE }}-OpenWrt-${{ env.BRANCH }}-Firmware
    #    path: ${{ env.FIRMWARE }}

    ## ä¸Šä¼ å›ºä»¶åˆ°å¥¶ç‰›å¿«ä¼ 
    #- name: Upload Firmware To CowTransfer
    #  if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
    #  run: |
    #    curl -fsSL git.io/file-transfer | sh
    #    ./transfer cow --block 2621440 -s -p 99 -t 3 --hash --no-progress ${FIRMWARE} 2>&1 | tee anothercowtransfer.log
    #    echo "::warning file=cowtransfer.com::$(cat anothercowtransfer.log | grep https)"
    #    echo "::set-env name=COWTRANSFER_URL::$(cat anothercowtransfer.log | grep https | cut -f3 -d" ")"
    
    #- name: Upload firmware to WeTransfer
    #  if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
    #  run: |
    #    curl -fsSL git.io/file-transfer | sh
    #    ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
    #    echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
    #    echo "::set-env name=WETRANSFER_URL::$(cat wetransfer.log | grep https | cut -f3 -d" ")"

    ## ç”Ÿæˆæ ‡ç­¾
    #- name: Generate Tag
    #  id: tag
    #  if: steps.compile.outputs.status == 'success' && env.CREATE_RELEASE == 'true' && !cancelled()
    #  run: |
    #    echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y-%m-%d")"
    #    echo "::set-output name=status::success"
    
    ## å‘è¡Œå›ºä»¶
    #- name: Upload Firmware To Release
    #  uses: softprops/action-gh-release@v1
    #  if: steps.tag.outputs.status == 'success' && !cancelled()
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    #  with:
    #    name: Netgear ${{ env.BRANCH }} ğŸš€ | è‡ªåŠ¨ç¼–è¯‘ / ${{ env.RELEASE_TAG }}
    #    tag_name: ${{ env.RELEASE_DATE }}
    #    body: |            
    #        1ã€æœ¬å›ºä»¶ä¸ºè‡ªåŠ¨ç¼–è¯‘
    #        2ã€å‘è¡Œç‰ˆä¸­åªæä¾›å®Œæ•´çš„å›ºä»¶
    #        3ã€éœ€è¦å•ç‹¬IPKè¯·åˆ°åˆ†æ”¯ä¸‹è½½
    #        4ã€æºç ï¼š${{ env.REPO_URL }}
    #        -- Build by ${{ env.BUILD_USER }} @ with Github Action on ${{ env.RELEASE_DATE }}
    #        ğŸš€ Auto build | è‡ªåŠ¨ç¼–è¯‘
    #        ğŸ”— [Cowtransfer | å¥¶ç‰›å¿«ä¼ ](${{ env.COWTRANSFER_URL }}) 
    #        ğŸ”— [WeTransfer](${{ env.WETRANSFER_URL }})       
    #        ğŸš€ ALL IPK | æœ¬å›ºä»¶ç¼–è¯‘çš„ipk
    #        ğŸ”— [Cowtransfer | å¥¶ç‰›å¿«ä¼ ](${{ env.IPK_URL }}) 
    #        å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ï¼ˆç¼–è¯‘å‰çš„æœ€åä¸€æ¬¡å¤§é›•æºç æ›´æ–°è®°å½•ï¼‰            
    #        ${{ env.useVersionInfo }}
    #        ${{ github.event.commits[0].message }}
    #    files: ${{ env.FIRMWARE }}/*

    ## å¾®ä¿¡é€šçŸ¥
    #- name: WeChat Notification
    #  if: steps.compile.outputs.status == 'success' && env.SEND_WECHAT_MSG == 'true' && !cancelled()
    #  uses: emon100/Action-Serverchan@master
    #  with:
    #    SCKEY: ${{ secrets.SCKEY }}
    #    text: ${{ env.BRANCH }}å›ºä»¶ç¼–è¯‘å®Œæˆï¼
    #    desp: æºç :${{ env.REPO_URL }} åˆ†æ”¯ï¼š${{ env.REPO_BRANCH }}
